name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn
      - name: Build docs
        run: yarn build:doc
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docz/dist
